language: java

os:
  - linux
dist:
  - bionic
jdk:
#  - oraclejdk13
  - openjdk13

before_install:
  - pwd
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER
  - echo $TRAVIS_REPO_SLUG

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - "mvn verify -e"
