name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'

    - name: Build with Maven
      run: mvn -T 1C install

    - name: Publish JAR to GitHub Packages
      uses: actions/upload-artifact@v2
      with:
        name: Application.jar
        path: target/Application.jar
      env:
        GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}
