name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 13
      uses: actions/setup-java@v2
      with:
        java-version: 13

    - name: Build with Maven
      run: mvn -T 1C install

    - name: Publish JAR to GitHub Packages
      uses: actions/upload-artifact@v2
      with:
        name: Application.jar
        path: target/Application.jar
      env:
        GITHUB_TOKEN: ${{ secrets.BUILD_TOKEN }}
